<a href="https://colab.research.google.com/github/Vicks-2019/NLP/blob/master/Word_Generation_using_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from numpy import array
from keras.preprocessing.text import Tokenizer
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Embedding

In [3]:

# source text
data = """ Organizing a software company is a very specialized type of management skill\n
where experienced persons can turn the organizational problem into a unique benefit\n
There are two type of companies product based and service based company\n
A professional software company normally consists of at least dedicated team\n """

In [4]:
# integer encode text
tokenizer = Tokenizer()
tokenizer.fit_on_texts([data])
encoded_data= tokenizer.texts_to_sequences([data])[0]
encoded_data

[7,
 1,
 4,
 2,
 8,
 1,
 9,
 10,
 5,
 3,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 1,
 22,
 23,
 24,
 25,
 26,
 5,
 3,
 27,
 28,
 6,
 29,
 30,
 6,
 2,
 1,
 31,
 4,
 2,
 32,
 33,
 3,
 34,
 35,
 36,
 37]

In [5]:
# determine the vocabulary size
vocab_size = len(tokenizer.word_index) + 1  # 0 is reserved for padding so that's why we added 1

print('Vocabulary Size: %d' % vocab_size)

Vocabulary Size: 38


In [6]:
# create word -> word sequences
sequences = list()
for i in range(1, len(encoded_data)):
	sequence = encoded_data[i-1:i+1]
	sequences.append(sequence)
print('Total Sequences: %d' % len(sequences))
# split into X and y elements

Total Sequences: 46


In [7]:

sequences
#sequences[:5] # [input, output]

[[7, 1],
 [1, 4],
 [4, 2],
 [2, 8],
 [8, 1],
 [1, 9],
 [9, 10],
 [10, 5],
 [5, 3],
 [3, 11],
 [11, 12],
 [12, 13],
 [13, 14],
 [14, 15],
 [15, 16],
 [16, 17],
 [17, 18],
 [18, 19],
 [19, 20],
 [20, 21],
 [21, 1],
 [1, 22],
 [22, 23],
 [23, 24],
 [24, 25],
 [25, 26],
 [26, 5],
 [5, 3],
 [3, 27],
 [27, 28],
 [28, 6],
 [6, 29],
 [29, 30],
 [30, 6],
 [6, 2],
 [2, 1],
 [1, 31],
 [31, 4],
 [4, 2],
 [2, 32],
 [32, 33],
 [33, 3],
 [3, 34],
 [34, 35],
 [35, 36],
 [36, 37]]

In [8]:

sequences = array(sequences)
X, y = sequences[:,0],sequences[:,1]

In [9]:
X[:5]

array([7, 1, 4, 2, 8])

In [10]:
y[:5]

array([1, 4, 2, 8, 1])

In [11]:
# one hot encode outputs
y = to_categorical(y, num_classes=vocab_size)
# define model
y[:5]

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.]], dtype=float32)

In [12]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=1))
model.add(LSTM(50))
model.add(Dense(vocab_size, activation='softmax'))
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 1, 10)             380       
_________________________________________________________________
lstm (LSTM)                  (None, 50)                12200     
_________________________________________________________________
dense (Dense)                (None, 38)                1938      
Total params: 14,518
Trainable params: 14,518
Non-trainable params: 0
_________________________________________________________________
None


In [13]:
# compile network
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [14]:

# fit network
model.fit(X, y, epochs=80)

Epoch 1/80
2/2 [==============================] - 0s 4ms/step - loss: 3.6378 - accuracy: 0.0217
Epoch 2/80
2/2 [==============================] - 0s 3ms/step - loss: 3.6363 - accuracy: 0.0652
Epoch 3/80
2/2 [==============================] - 0s 3ms/step - loss: 3.6352 - accuracy: 0.0870
Epoch 4/80
2/2 [==============================] - 0s 3ms/step - loss: 3.6341 - accuracy: 0.0870
Epoch 5/80
2/2 [==============================] - 0s 3ms/step - loss: 3.6330 - accuracy: 0.0870
Epoch 6/80
2/2 [==============================] - 0s 3ms/step - loss: 3.6319 - accuracy: 0.0870
Epoch 7/80
2/2 [==============================] - 0s 3ms/step - loss: 3.6309 - accuracy: 0.0870
Epoch 8/80
2/2 [==============================] - 0s 3ms/step - loss: 3.6296 - accuracy: 0.0870
Epoch 9/80
2/2 [==============================] - 0s 3ms/step - loss: 3.6286 - accuracy: 0.0870
Epoch 10/80
2/2 [==============================] - 0s 2ms/step - loss: 3.6273 - accuracy: 0.0870
Epoch 11/80
2/2 [======================

In [23]:
# generate a sequence from the model
def generate_seq(model, tokenizer, enter_text, n_pred):  
	in_text, result = enter_text, enter_text  # 
	# generate a fixed number of words
	for _ in range(n_pred):
        
		# encode the text as integer
		encoded = tokenizer.texts_to_sequences([in_text])[0]
		encoded = array(encoded)
        
		# predict a word in the vocabulary
		yhat = model.predict_classes(encoded)
        
		# map predicted word index to word
		out_word = ''
		for word, index in tokenizer.word_index.items():
			if index == yhat:
				out_word = word
				break
		# append to input
		in_text, result = out_word, result + ' ' + out_word
	return result

In [25]:

# evaluate
print(generate_seq(model, tokenizer, 'software', 6))

software a a a a a a


In [27]:
# evaluate
print(generate_seq(model, tokenizer, 'product', 3))

product based a a
